title = Grocery App
package.name = groceryapp
package.domain = org.test
source.include_exts = py,png,jpg,kv,atlas,ttf,ttc,otf
orientation = portrait
fullscreen = 1
android.api = 30
android.build_tools = 34.0.0
android.minapi = 21
requirements = python3,kivy,plyer,requests,pillow
android.permissions = INTERNET
android.hostpython = 3
android.ndk = 23b
android.ndk_path = ~/.buildozer/android/platform/android-ndk-r23b
android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
